export const FETCH_POST_REQUEST = 'FETCH_POST_REQUEST';
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
export const FETCH_POST_FAILED = 'FETCH_POST_FAILED';

export const FETCH_POST_DETAIL_REQUEST = 'FETCH_POST_REQUEST';
export const FETCH_POST_DETAIL_SUCCESS = 'FETCH_POST_SUCCESS';
export const FETCH_POST_DETAIL_FAILED = 'FETCH_POST_FAILED';

export const SORT_POSTS_ASC = 'SORT_POSTS_ASC';
export const SORT_POSTS_DESC = 'SORT_POSTS_DESC';

export const SEARCH_POSTS = 'SEARCH_POSTS';

export const LOCAL_THEME = 'LOCAL_THEME';

export const SET_FILTER_POST_FIELD = 'SET_FILTER_POST_FIELD'
export const CLEAR_FILTER_POST_FIELDS = 'CLEAR_FILTER_POST_FIELDS'