export const FETCH_POST_REQUEST = 'FETCH_POST_REQUEST';
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
export const FETCH_POST_FAILED = 'FETCH_POST_FAILED';

export const FETCH_POST_DETAIL_REQUEST = 'FETCH_POST_REQUEST';
export const FETCH_POST_DETAIL_SUCCESS = 'FETCH_POST_SUCCESS';
export const FETCH_POST_DETAIL_FAILED = 'FETCH_POST_FAILED';

export const FETCH_COLOR_REQUEST = 'FETCH_COLOR_REQUEST';
export const FETCH_COLOR_SUCCESS = 'FETCH_COLOR_SUCCESS';
export const FETCH_COLOR_FAILED = 'FETCH_COLOR_FAILED';

export const SORT_POSTS_ASC = 'SORT_POSTS_ASC';
export const SORT_POSTS_DESC = 'SORT_POSTS_DESC';

export const SEARCH_POSTS = 'SEARCH_POSTS';

export const LOCAL_THEME = 'LOCAL_THEME';

export const SET_FILTER_POST_FIELD = 'SET_FILTER_POST_FIELD'
export const CLEAR_FILTER_POST_FIELDS = 'CLEAR_FILTER_POST_FIELDS'

export const SET_PAGE = 'SET_PAGE'
export const SET_MODAL = 'SET_MODAL'
export const SET_IMAGE = 'SET_IMAGE'